# Generated by Django 3.2.7 on 2021-09-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table='faculty',
        ),
    ]
