# Generated by Django 3.2.7 on 2021-09-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_faculty_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table='faculty',
        ),
    ]
